#pragma once
#include <functional>
#define WIN32_LEAN_AND_MEAN
#include <SDKDDKVer.h>
#include <windows.h>
#include <stdlib.h>
#include <malloc.h>
#include <memory.h>
#include <tchar.h>
#include <memory>
#include <vector>
#include <string>
#include <array>
#include <mutex>
#include <shared_mutex>
#include <cmath>
#include <algorithm>
#include <windowsx.h>